# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :prepare4Release do
  desc "copy resource of #{PROFILE_NAME} into relative folder"

  #copy resource of iOS
  sh("cp -rf ../profiles/#{PROFILE_NAME}/ios/Images.xcassets/ ../ios/TARGET_NAME/Images.xcassets/")

  #copy resource of Android
  sh("cp -rf ../profiles/#{PROFILE_NAME}/android/ ../android/app/src/main/res/")
end

platform :ios do
#  desc "Push a new beta build to TestFlight"
#  lane :beta do
#    increment_build_number(xcodeproj: "MovieApp.xcodeproj")
#    build_app(workspace: "MovieApp.xcworkspace", scheme: "MovieApp")
# end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    cert
    sigh(force: true)
  end
end
