# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

MY_APP_ID = "org.parallelapps.movieapp"
MY_PROFILE = "match AppStore org.parallelapps.movieapp"

default_platform(:ios)

lane :prepare4Release do
  desc "copy resource of #{PROFILE_NAME} into relative folder"

  #copy resource of iOS
  sh("cp -rf ../profiles/#{PROFILE_NAME}/ios/Images.xcassets/ ../ios/TARGET_NAME/Images.xcassets/")

  #copy resource of Android
  sh("cp -rf ../profiles/#{PROFILE_NAME}/android/ ../android/app/src/main/res/")
end

platform :ios do
#  desc "Push a new beta build to TestFlight"
#  lane :beta do
#    increment_build_number(xcodeproj: "MovieApp.xcodeproj")
#    build_app(workspace: "MovieApp.xcworkspace", scheme: "MovieApp")
# end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_ios_app(export_method: 'development')
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './MovieApp.xcodeproj')
    push_to_git_remote
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'org.parallelapps.movieapp', type: 'development', readonly: true)
    match(app_identifier: 'org.parallelapps.movieapp', type: 'appstore', readonly: true)
  end

  lane :build do
    certificates
    increment_build_number(xcodeproj: './MovieApp.xcodeproj')
    gym(scheme: 'MovieApp', project: './MovieApp.xcodeproj')
  end

  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: './MovieApp.xcodeproj')
    build_app
    enable_automatic_code_signing(path: './MovieApp.xcodeproj')
    upload_to_testflight
#    produce(
#      username: "derekmartin1@gmail.com",
#      app_identifier: "org.parallelapps.movieapp",
#      app_name: "MovieApp for iOS",
##      app_version: "1.0",
  #  )
  end
end
